//! Stable Indexing operation identity and deterministic assigned-entity identity.
//!
//! `IndexId` identifies an Index Assignment Operation. Its existing Phase 2
//! deterministic generation scheme remains frozen: the identity is exactly
//! 64 bytes and is derived from the logical indexing operation inputs.
//!
//! `IndexAssignedId` is a separate Indexing-owned identity for the referenced
//! source object. It is deterministically derived only from the opaque target
//! reference type and source-owned object reference. It deliberately does not
//! depend on `IndexId`, index-definition metadata, key material, version values,
//! or Core request/event identifiers.
//!
//! Both mechanisms use domain-separated BLAKE3 extendable-output hashing. These
//! identity mechanisms are not general-purpose serialization formats and do not
//! assign semantic meaning to source-owned values.

use core::fmt;
use std::error::Error;

use blake3::Hasher;

use crate::identity::definition::IndexDefinitionId;
use crate::identity::namespace::IndexNamespace;
use crate::index::{
    IndexFamily, KeyMaterial, KeyMaterialValidationError, ObjectReference, TargetReferenceType,
};

/// Fixed width of an [`IndexId`] in bytes.
pub const INDEX_ID_BYTE_LEN: usize = 64;

/// Fixed width of an [`IndexId`] in bits.
pub const INDEX_ID_BIT_LEN: usize = INDEX_ID_BYTE_LEN * 8;

/// Domain-separation context for Index Assignment Operation identity generation.
///
/// The domain is intentionally explicit so that `IndexId` generation does not
/// share an unqualified hash namespace with unrelated Nizaam systems.
const INDEX_ID_GENERATION_DOMAIN: &[u8] = b"NIZAAM / INDEX-ID / ";

/// Version of the frozen Phase 2 Index Assignment Operation ID generation scheme.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct IndexIdGenerationVersion(u32);

impl IndexIdGenerationVersion {
    /// The currently defined IndexId generation scheme.
    pub const CURRENT: Self = Self(1);

    /// Creates an explicit generation-scheme version.
    ///
    /// Version values are opaque scheme identifiers. The current Phase 2
    /// contract uses [`Self::CURRENT`].
    #[must_use]
    pub const fn new(value: u32) -> Self {
        Self(value)
    }

    /// Returns the numeric generation-scheme version.
    #[must_use]
    pub const fn value(self) -> u32 {
        self.0
    }
}

impl fmt::Display for IndexIdGenerationVersion {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Failures that can occur while generating an [`IndexId`].
#[derive(Debug, Eq, PartialEq)]
pub enum IndexIdGenerationError {
    /// The supplied key material violates its logical validation contract.
    InvalidKeyMaterial(KeyMaterialValidationError),

    /// The requested generation-scheme version is not supported.
    UnsupportedVersion {
        requested: IndexIdGenerationVersion,
        supported: IndexIdGenerationVersion,
    },
}

impl fmt::Display for IndexIdGenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidKeyMaterial(error) => {
                write!(
                    formatter,
                    "invalid key material for IndexId generation: {error}"
                )
            }
            Self::UnsupportedVersion {
                requested,
                supported,
            } => write!(
                formatter,
                "unsupported IndexId generation version {requested}; supported version is {supported}"
            ),
        }
    }
}

impl Error for IndexIdGenerationError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::InvalidKeyMaterial(error) => Some(error),
            Self::UnsupportedVersion { .. } => None,
        }
    }
}

impl From<KeyMaterialValidationError> for IndexIdGenerationError {
    fn from(error: KeyMaterialValidationError) -> Self {
        Self::InvalidKeyMaterial(error)
    }
}

/// Stable identity of one Index Assignment Operation.
///
/// The underlying value is exactly 64 bytes (512 bits). The value is opaque:
/// callers can compare, store, and transport it, but the type does not expose
/// any semantic interpretation of the generated bytes.
///
/// `IndexId` identifies the indexing operation itself. It is not the identity
/// assigned to the referenced source object.
///
/// `from_bytes` remains available as the low-level constructor for established
/// binary identity values and for Phase 1 compatibility. New deterministic
/// operation identities should use [`IndexId::generate`].
#[derive(Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct IndexId([u8; INDEX_ID_BYTE_LEN]);

impl IndexId {
    /// Returns the fixed number of bytes in an `IndexId`.
    #[must_use]
    pub const fn byte_len() -> usize {
        INDEX_ID_BYTE_LEN
    }

    /// Returns the fixed number of bits in an `IndexId`.
    #[must_use]
    pub const fn bit_len() -> usize {
        INDEX_ID_BIT_LEN
    }

    /// Returns the generation-scheme version used by [`Self::generate`].
    #[must_use]
    pub const fn generation_version() -> IndexIdGenerationVersion {
        IndexIdGenerationVersion::CURRENT
    }

    /// Constructs an `IndexId` from its complete fixed-width binary value.
    ///
    /// This is the low-level binary constructor. It does not itself perform
    /// hashing or canonicalization.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; INDEX_ID_BYTE_LEN]) -> Self {
        Self(bytes)
    }

    /// Generates an `IndexId` for an Index Assignment Operation using the
    /// current Phase 2 generation scheme.
    ///
    /// The operation identity basis is:
    ///
    /// ```text
    /// namespace + definition identity (definition identifier + family) + key material
    /// ```
    ///
    /// These values are encoded deterministically, domain-separated, and
    /// versioned before standard BLAKE3 extendable-output hashing produces the
    /// exact 64-byte identity value.
    pub fn generate(
        namespace: &IndexNamespace,
        definition: &IndexDefinitionId,
        family: IndexFamily,
        key_material: &KeyMaterial,
    ) -> Result<Self, IndexIdGenerationError> {
        Self::generate_with_version(
            Self::generation_version(),
            namespace,
            definition,
            family,
            key_material,
        )
    }

    /// Generates an `IndexId` using an explicit generation-scheme version.
    ///
    /// The public API keeps the generation-scheme version separate from
    /// `IndexVersion`, `SourceVersion`, `SchemaVersion`, and Core contract
    /// versions. This makes the scheme explicit if a future compatible
    /// generation version is introduced.
    pub fn generate_with_version(
        generation_version: IndexIdGenerationVersion,
        namespace: &IndexNamespace,
        definition: &IndexDefinitionId,
        family: IndexFamily,
        key_material: &KeyMaterial,
    ) -> Result<Self, IndexIdGenerationError> {
        if generation_version != Self::generation_version() {
            return Err(IndexIdGenerationError::UnsupportedVersion {
                requested: generation_version,
                supported: Self::generation_version(),
            });
        }

        key_material.validate()?;

        let canonical = canonical_generation_bytes(
            generation_version,
            namespace,
            definition,
            family,
            key_material,
        );

        let mut output = [0_u8; INDEX_ID_BYTE_LEN];
        let mut hasher = Hasher::new();
        hasher.update(&canonical);
        hasher.finalize_xof().fill(&mut output);

        Ok(Self::from_bytes(output))
    }

    /// Returns the exact underlying 64-byte identity value.
    ///
    /// This accessor does not expose any semantic interpretation of the
    /// identity. It only permits efficient comparison, storage, or transport
    /// by later layers.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; INDEX_ID_BYTE_LEN] {
        &self.0
    }

    /// Consumes the identity and returns its exact underlying bytes.
    #[must_use]
    pub const fn into_bytes(self) -> [u8; INDEX_ID_BYTE_LEN] {
        self.0
    }
}

impl AsRef<[u8; INDEX_ID_BYTE_LEN]> for IndexId {
    fn as_ref(&self) -> &[u8; INDEX_ID_BYTE_LEN] {
        self.as_bytes()
    }
}

impl AsRef<[u8]> for IndexId {
    fn as_ref(&self) -> &[u8] {
        self.as_bytes()
    }
}

impl fmt::Debug for IndexId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.debug_tuple("IndexId").field(&self.0).finish()
    }
}

/// Fixed width of the binary portion of an [`IndexAssignedId`] in bytes.
pub const INDEX_ASSIGNED_ID_BYTE_LEN: usize = 64;

/// Fixed width of the binary portion of an [`IndexAssignedId`] in bits.
pub const INDEX_ASSIGNED_ID_BIT_LEN: usize = INDEX_ASSIGNED_ID_BYTE_LEN * 8;

/// Domain-separation context for assigned-entity identity generation.
///
/// The assigned-entity identity has a separate hash namespace from `IndexId`.
const INDEX_ASSIGNED_ID_GENERATION_DOMAIN: &[u8] = b"NIZAAM / INDEX-ASSIGNED-ID / ";

/// Stable identity assigned by Indexing to one referenced source object.
///
/// `IndexAssignedId` is intentionally distinct from [`IndexId`]:
///
/// - [`IndexId`] identifies the Index Assignment Operation.
/// - `IndexAssignedId` identifies the referenced object for which the ID was
///   assigned.
///
/// The binary identity is exactly 64 bytes (512 bits). The target-reference
/// type is retained alongside the binary value so the public textual form is:
///
/// ```text
/// <TargetReferenceType>-<128 lowercase hexadecimal characters>
/// ```
///
/// The binary identity is derived only from the target-reference type and the
/// source-owned [`ObjectReference`]. Indexing does not interpret the object
/// reference or create a domain-specific entity model.
#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct IndexAssignedId {
    target_reference_type: TargetReferenceType,
    value: [u8; INDEX_ASSIGNED_ID_BYTE_LEN],
}

impl IndexAssignedId {
    /// Returns the fixed number of bytes in the binary identity portion.
    #[must_use]
    pub const fn byte_len() -> usize {
        INDEX_ASSIGNED_ID_BYTE_LEN
    }

    /// Returns the fixed number of bits in the binary identity portion.
    #[must_use]
    pub const fn bit_len() -> usize {
        INDEX_ASSIGNED_ID_BIT_LEN
    }

    /// Generates an assigned-entity identity from an opaque target-reference
    /// type and source-owned object reference.
    ///
    /// No `IndexId`, index-definition metadata, key material, version value, or
    /// Core request/event identity participates in generation. Consequently,
    /// separate assignment operations referring to the same target produce the
    /// same `IndexAssignedId`.
    #[must_use]
    pub fn generate(
        target_reference_type: &TargetReferenceType,
        object_reference: &ObjectReference,
    ) -> Self {
        let canonical =
            canonical_assigned_id_generation_bytes(target_reference_type, object_reference);

        let mut output = [0_u8; INDEX_ASSIGNED_ID_BYTE_LEN];
        let mut hasher = Hasher::new();
        hasher.update(&canonical);
        hasher.finalize_xof().fill(&mut output);

        Self {
            target_reference_type: target_reference_type.clone(),
            value: output,
        }
    }

    /// Constructs an assigned-entity identity from an existing binary value
    /// and its target-reference type.
    ///
    /// This is the low-level constructor for established identity values. It
    /// does not perform hashing or canonicalization.
    #[must_use]
    pub fn from_parts(
        target_reference_type: TargetReferenceType,
        bytes: [u8; INDEX_ASSIGNED_ID_BYTE_LEN],
    ) -> Self {
        Self {
            target_reference_type,
            value: bytes,
        }
    }

    /// Returns the opaque target-reference type associated with this identity.
    #[must_use]
    pub fn target_reference_type(&self) -> &TargetReferenceType {
        &self.target_reference_type
    }

    /// Returns the exact underlying 64-byte binary identity value.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; INDEX_ASSIGNED_ID_BYTE_LEN] {
        &self.value
    }

    /// Consumes the identity and returns its exact underlying bytes.
    #[must_use]
    pub fn into_bytes(self) -> [u8; INDEX_ASSIGNED_ID_BYTE_LEN] {
        self.value
    }
}

impl AsRef<[u8; INDEX_ASSIGNED_ID_BYTE_LEN]> for IndexAssignedId {
    fn as_ref(&self) -> &[u8; INDEX_ASSIGNED_ID_BYTE_LEN] {
        self.as_bytes()
    }
}

impl AsRef<[u8]> for IndexAssignedId {
    fn as_ref(&self) -> &[u8] {
        self.as_bytes()
    }
}

impl fmt::Debug for IndexAssignedId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("IndexAssignedId")
            .field("target_reference_type", &self.target_reference_type)
            .field("value", &self.value)
            .finish()
    }
}

impl fmt::Display for IndexAssignedId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.target_reference_type.as_str())?;
        formatter.write_str("-")?;
        write_hex(&self.value, formatter)
    }
}

/// Produces the canonical, domain-separated byte representation consumed by
/// BLAKE3 for `IndexAssignedId` generation.
///
/// Encoding contract:
///
/// ```text
/// domain bytes
/// +
/// length-prefixed target-reference type
/// +
/// length-prefixed object-reference source
/// +
/// length-prefixed opaque object reference
/// ```
///
/// Every component is length-delimited so concatenation is unambiguous.
fn canonical_assigned_id_generation_bytes(
    target_reference_type: &TargetReferenceType,
    object_reference: &ObjectReference,
) -> Vec<u8> {
    let mut bytes = Vec::new();
    bytes.extend_from_slice(INDEX_ASSIGNED_ID_GENERATION_DOMAIN);
    encode_bytes(target_reference_type.as_str().as_bytes(), &mut bytes);
    encode_bytes(object_reference.source().as_bytes(), &mut bytes);
    encode_bytes(object_reference.object_reference().as_bytes(), &mut bytes);
    bytes
}

fn write_hex(bytes: &[u8], formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    for &byte in bytes {
        write!(formatter, "{byte:02x}")?;
    }

    Ok(())
}

/// Produces the canonical, domain-separated byte representation consumed by
/// BLAKE3 for IndexId generation.
///
/// Encoding contract:
///
/// ```text
/// domain bytes
/// +
/// generation version (u32, big-endian)
/// +
/// length-prefixed namespace
/// +
/// length-prefixed definition identifier
/// +
/// length-prefixed canonical key material
/// ```
///
/// Every component is length-delimited so concatenation is unambiguous. The
/// key component uses [`KeyMaterial::canonical_bytes`] rather than caller
/// serialization.
fn canonical_generation_bytes(
    generation_version: IndexIdGenerationVersion,
    namespace: &IndexNamespace,
    definition: &IndexDefinitionId,
    family: IndexFamily,
    key_material: &KeyMaterial,
) -> Vec<u8> {
    let key_bytes = key_material.canonical_bytes();

    let mut bytes = Vec::new();
    bytes.extend_from_slice(INDEX_ID_GENERATION_DOMAIN);
    bytes.extend_from_slice(&generation_version.value().to_be_bytes());
    encode_bytes(namespace.as_str().as_bytes(), &mut bytes);
    encode_bytes(definition.as_str().as_bytes(), &mut bytes);
    encode_family(family, &mut bytes);
    encode_bytes(&key_bytes, &mut bytes);
    bytes
}

fn encode_family(family: IndexFamily, output: &mut Vec<u8>) {
    let tag = match family {
        IndexFamily::Identity => 0x01,
        IndexFamily::Inverted => 0x02,
        IndexFamily::Relationship => 0x03,
        IndexFamily::Similarity => 0x04,
    };
    output.push(tag);
}

fn encode_bytes(value: &[u8], output: &mut Vec<u8>) {
    output.extend_from_slice(&(value.len() as u64).to_be_bytes());
    output.extend_from_slice(value);
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    fn sample_bytes(seed: u8) -> [u8; INDEX_ID_BYTE_LEN] {
        let mut bytes = [0_u8; INDEX_ID_BYTE_LEN];

        for (index, byte) in bytes.iter_mut().enumerate() {
            *byte = seed.wrapping_add(index as u8);
        }

        bytes
    }

    fn namespace() -> IndexNamespace {
        IndexNamespace::new("quran.text").expect("test namespace must be valid")
    }

    fn definition() -> IndexDefinitionId {
        IndexDefinitionId::new("verse-term").expect("test definition ID must be valid")
    }

    fn key_material(value: &str) -> KeyMaterial {
        KeyMaterial::text(value)
    }

    fn generated_id(
        namespace: &IndexNamespace,
        definition: &IndexDefinitionId,
        family: IndexFamily,
        key_material: &KeyMaterial,
    ) -> IndexId {
        IndexId::generate(namespace, definition, family, key_material)
            .expect("test generation inputs must be valid")
    }

    #[test]
    fn constants_define_the_required_512_bit_width() {
        assert_eq!(INDEX_ID_BYTE_LEN, 64);
        assert_eq!(INDEX_ID_BIT_LEN, 512);
        assert_eq!(IndexId::byte_len(), 64);
        assert_eq!(IndexId::bit_len(), 512);
    }

    #[test]
    fn generation_version_is_distinct_and_explicit() {
        assert_eq!(IndexIdGenerationVersion::CURRENT.value(), 1);
        assert_eq!(
            IndexId::generation_version(),
            IndexIdGenerationVersion::CURRENT
        );
        assert_ne!(
            IndexIdGenerationVersion::CURRENT,
            IndexIdGenerationVersion::new(2)
        );
    }

    #[test]
    fn generate_is_deterministic_for_identical_assignment_operation_input() {
        let namespace = namespace();
        let definition = definition();
        let key = key_material("lemma");

        let first = generated_id(&namespace, &definition, IndexFamily::Inverted, &key);
        let second = generated_id(&namespace, &definition, IndexFamily::Inverted, &key);

        assert_eq!(first, second);
    }

    #[test]
    fn changing_namespace_changes_generated_index_id() {
        let first_namespace = IndexNamespace::new("quran.text").expect("namespace must be valid");
        let second_namespace = IndexNamespace::new("quran.word").expect("namespace must be valid");
        let definition = definition();
        let key = key_material("lemma");

        let first = generated_id(&first_namespace, &definition, IndexFamily::Inverted, &key);
        let second = generated_id(&second_namespace, &definition, IndexFamily::Inverted, &key);

        assert_ne!(first, second);
    }

    #[test]
    fn changing_definition_changes_generated_index_id() {
        let namespace = namespace();
        let first_definition =
            IndexDefinitionId::new("verse-term").expect("definition must be valid");
        let second_definition =
            IndexDefinitionId::new("verse-lemma").expect("definition must be valid");
        let key = key_material("lemma");

        let first = generated_id(&namespace, &first_definition, IndexFamily::Inverted, &key);
        let second = generated_id(&namespace, &second_definition, IndexFamily::Inverted, &key);

        assert_ne!(first, second);
    }

    #[test]
    fn changing_index_family_changes_generated_index_id() {
        let namespace = namespace();
        let definition = definition();
        let key = key_material("lemma");

        let first = generated_id(&namespace, &definition, IndexFamily::Identity, &key);
        let second = generated_id(&namespace, &definition, IndexFamily::Inverted, &key);

        assert_ne!(first, second);
    }

    #[test]
    fn changing_key_material_changes_generated_index_id() {
        let namespace = namespace();
        let definition = definition();
        let first_key = key_material("lemma");
        let second_key = key_material("root");

        let first = generated_id(&namespace, &definition, IndexFamily::Inverted, &first_key);
        let second = generated_id(&namespace, &definition, IndexFamily::Inverted, &second_key);

        assert_ne!(first, second);
    }

    #[test]
    fn generated_index_id_is_exactly_64_bytes() {
        let id = generated_id(
            &namespace(),
            &definition(),
            IndexFamily::Inverted,
            &key_material("lemma"),
        );

        assert_eq!(id.as_bytes().len(), 64);
        assert_eq!(IndexId::byte_len(), 64);
        assert_eq!(IndexId::bit_len(), 512);
    }

    #[test]
    fn key_material_validation_is_enforced_before_generation() {
        let invalid = KeyMaterial::text("bad\nvalue");

        let error = IndexId::generate(&namespace(), &definition(), IndexFamily::Inverted, &invalid)
            .expect_err("invalid key material must be rejected");

        assert!(matches!(
            error,
            IndexIdGenerationError::InvalidKeyMaterial(
                KeyMaterialValidationError::TextControlCharacter { .. }
            )
        ));
    }

    #[test]
    fn canonical_generation_input_is_deterministic() {
        let namespace = namespace();
        let definition = definition();
        let key = key_material("lemma");

        let first = canonical_generation_bytes(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &definition,
            IndexFamily::Inverted,
            &key,
        );
        let second = canonical_generation_bytes(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &definition,
            IndexFamily::Inverted,
            &key,
        );

        assert_eq!(first, second);
    }

    #[test]
    fn canonical_generation_input_has_unambiguous_component_boundaries() {
        let left = IndexDefinitionId::new("bc").expect("definition must be valid");
        let right = IndexDefinitionId::new("c").expect("definition must be valid");
        let namespace = IndexNamespace::new("a").expect("namespace must be valid");
        let key = KeyMaterial::text("k");

        let first = canonical_generation_bytes(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &left,
            IndexFamily::Inverted,
            &key,
        );
        let second = canonical_generation_bytes(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &right,
            IndexFamily::Inverted,
            &key,
        );

        assert_ne!(first, second);
    }

    #[test]
    fn generation_version_participates_in_the_canonical_input_and_unsupported_versions_are_rejected()
     {
        let namespace = namespace();
        let definition = definition();
        let key = key_material("lemma");

        let first_bytes = canonical_generation_bytes(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &definition,
            IndexFamily::Inverted,
            &key,
        );
        let second_bytes = canonical_generation_bytes(
            IndexIdGenerationVersion::new(2),
            &namespace,
            &definition,
            IndexFamily::Inverted,
            &key,
        );

        assert_ne!(first_bytes, second_bytes);

        let first = IndexId::generate_with_version(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &definition,
            IndexFamily::Inverted,
            &key,
        )
        .expect("current generation version should succeed");
        assert!(
            IndexId::generate_with_version(
                IndexIdGenerationVersion::new(2),
                &namespace,
                &definition,
                IndexFamily::Inverted,
                &key,
            )
            .is_err()
        );

        assert_ne!(first, IndexId::from_bytes([0_u8; INDEX_ID_BYTE_LEN]));
    }

    #[test]
    fn unsupported_generation_version_is_reported_explicitly() {
        let error = IndexId::generate_with_version(
            IndexIdGenerationVersion::new(2),
            &namespace(),
            &definition(),
            IndexFamily::Inverted,
            &key_material("lemma"),
        )
        .expect_err("unsupported generation version must be rejected");

        assert_eq!(
            error,
            IndexIdGenerationError::UnsupportedVersion {
                requested: IndexIdGenerationVersion::new(2),
                supported: IndexIdGenerationVersion::CURRENT,
            }
        );
        assert!(std::error::Error::source(&error).is_none());
        assert!(
            error
                .to_string()
                .contains("unsupported IndexId generation version")
        );
    }

    #[test]
    fn domain_separation_is_part_of_the_hashed_input() {
        let namespace = namespace();
        let definition = definition();
        let key = key_material("lemma");
        let canonical = canonical_generation_bytes(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &definition,
            IndexFamily::Inverted,
            &key,
        );

        let mut unqualified = [0_u8; INDEX_ID_BYTE_LEN];
        let mut hasher = blake3::Hasher::new();
        hasher.update(&canonical[INDEX_ID_GENERATION_DOMAIN.len() + core::mem::size_of::<u32>()..]);
        hasher.finalize_xof().fill(&mut unqualified);

        let generated = generated_id(&namespace, &definition, IndexFamily::Inverted, &key);

        assert_ne!(generated.as_bytes(), &unqualified);
    }

    #[test]
    fn generated_id_matches_the_explicit_blake3_xof_contract() {
        let namespace = namespace();
        let definition = definition();
        let key = key_material("lemma");
        let canonical = canonical_generation_bytes(
            IndexIdGenerationVersion::CURRENT,
            &namespace,
            &definition,
            IndexFamily::Inverted,
            &key,
        );

        let mut expected = [0_u8; INDEX_ID_BYTE_LEN];
        let mut hasher = blake3::Hasher::new();
        hasher.update(&canonical);
        hasher.finalize_xof().fill(&mut expected);

        let actual = IndexId::generate(&namespace, &definition, IndexFamily::Inverted, &key)
            .expect("generation should succeed");

        assert_eq!(actual.as_bytes(), &expected);
    }

    #[test]
    fn generated_id_matches_a_fixed_known_answer_vector() {
        let namespace = IndexNamespace::new("quran.text").expect("namespace must be valid");
        let definition = IndexDefinitionId::new("verse-term").expect("definition must be valid");
        let key = KeyMaterial::text("lemma");

        let actual = IndexId::generate(&namespace, &definition, IndexFamily::Inverted, &key)
            .expect("generation should succeed");

        const EXPECTED_HEX: &str = "6f26138643aaca2e49a5645e5eae4f5341f96b05d20d8f5901aa2c1457a5f16313c0a57684af0c8329a4693a5785ba814d899e708d72cfcbd36835afa7b3d0c9";
        assert_eq!(hex_encode(actual.as_bytes()), EXPECTED_HEX);
    }

    fn hex_encode(bytes: &[u8]) -> String {
        const HEX: &[u8; 16] = b"0123456789abcdef";
        let mut encoded = String::with_capacity(bytes.len() * 2);
        for &byte in bytes {
            encoded.push(HEX[(byte >> 4) as usize] as char);
            encoded.push(HEX[(byte & 0x0f) as usize] as char);
        }
        encoded
    }

    #[test]
    fn from_bytes_preserves_the_complete_identity_value() {
        let bytes = sample_bytes(7);
        let id = IndexId::from_bytes(bytes);

        assert_eq!(id.as_bytes(), &bytes);
        assert_eq!(id.into_bytes(), bytes);
    }

    #[test]
    fn arbitrary_64_byte_values_are_valid_identity_values() {
        let mut bytes = [0_u8; INDEX_ID_BYTE_LEN];

        for (index, byte) in bytes.iter_mut().enumerate() {
            *byte = if index % 2 == 0 { 0x00 } else { 0xFF };
        }

        let id = IndexId::from_bytes(bytes);

        assert_eq!(id.as_bytes(), &bytes);
    }

    #[test]
    fn identical_values_are_equal() {
        let bytes = sample_bytes(11);

        let first = IndexId::from_bytes(bytes);
        let second = IndexId::from_bytes(bytes);

        assert_eq!(first, second);
    }

    #[test]
    fn different_values_are_not_equal() {
        let first = IndexId::from_bytes(sample_bytes(13));
        let second = IndexId::from_bytes(sample_bytes(14));

        assert_ne!(first, second);
    }

    #[test]
    fn ordering_is_determined_by_the_binary_identity_value() {
        let low = IndexId::from_bytes([0x00; INDEX_ID_BYTE_LEN]);
        let high = IndexId::from_bytes([0xFF; INDEX_ID_BYTE_LEN]);

        assert!(low < high);
        assert!(high > low);
    }

    #[test]
    fn hash_is_consistent_for_equal_identity_values() {
        let bytes = sample_bytes(21);
        let first = IndexId::from_bytes(bytes);
        let second = IndexId::from_bytes(bytes);

        let mut first_hasher = DefaultHasher::new();
        first.hash(&mut first_hasher);

        let mut second_hasher = DefaultHasher::new();
        second.hash(&mut second_hasher);

        assert_eq!(first_hasher.finish(), second_hasher.finish());
    }

    #[test]
    fn hash_is_compatible_with_binary_identity_difference() {
        let first = IndexId::from_bytes([0x00; INDEX_ID_BYTE_LEN]);
        let second = IndexId::from_bytes([0xFF; INDEX_ID_BYTE_LEN]);

        let mut first_hasher = DefaultHasher::new();
        first.hash(&mut first_hasher);

        let mut second_hasher = DefaultHasher::new();
        second.hash(&mut second_hasher);

        assert_ne!(first_hasher.finish(), second_hasher.finish());
    }

    #[test]
    fn clone_and_copy_preserve_identity() {
        let id = IndexId::from_bytes(sample_bytes(29));

        let cloned = id;
        let copied = IndexId::from_bytes(id.into_bytes());

        assert_eq!(id, cloned);
        assert_eq!(id, copied);
    }

    #[test]
    fn as_ref_exposes_the_same_binary_identity() {
        let bytes = sample_bytes(37);
        let id = IndexId::from_bytes(bytes);

        let fixed_width: &[u8; INDEX_ID_BYTE_LEN] = id.as_ref();
        let slice: &[u8] = id.as_ref();

        assert_eq!(fixed_width, &bytes);
        assert_eq!(slice, bytes.as_slice());
    }

    #[test]
    fn debug_output_identifies_the_type_without_defining_a_wire_encoding() {
        let id = IndexId::from_bytes([0xAB; INDEX_ID_BYTE_LEN]);
        let debug = format!("{id:?}");

        assert!(debug.starts_with("IndexId("));
        assert!(!debug.is_empty());
    }

    fn target_reference_type(value: &str) -> TargetReferenceType {
        TargetReferenceType::new(value).expect("test target-reference type must be valid")
    }

    fn object_reference(source: &str, reference: &str) -> ObjectReference {
        ObjectReference::new(source, reference).expect("test object reference must be valid")
    }

    #[test]
    fn assigned_id_has_the_required_512_bit_binary_width() {
        assert_eq!(INDEX_ASSIGNED_ID_BYTE_LEN, 64);
        assert_eq!(INDEX_ASSIGNED_ID_BIT_LEN, 512);
        assert_eq!(IndexAssignedId::byte_len(), 64);
        assert_eq!(IndexAssignedId::bit_len(), 512);
    }

    #[test]
    fn assigned_id_is_deterministic_for_identical_target_reference_input() {
        let target = target_reference_type("source.object");
        let reference = object_reference("quran", "verse:1:1");

        let first = IndexAssignedId::generate(&target, &reference);
        let second = IndexAssignedId::generate(&target, &reference);

        assert_eq!(first, second);
        assert_eq!(first.target_reference_type().as_str(), "source.object");
    }

    #[test]
    fn changing_target_reference_type_changes_assigned_id() {
        let first_target = target_reference_type("source.object");
        let second_target = target_reference_type("source.semantic");
        let reference = object_reference("quran", "verse:1:1");

        let first = IndexAssignedId::generate(&first_target, &reference);
        let second = IndexAssignedId::generate(&second_target, &reference);

        assert_ne!(first, second);
    }

    #[test]
    fn changing_object_reference_source_changes_assigned_id() {
        let target = target_reference_type("source.object");
        let first_reference = object_reference("quran", "verse:1:1");
        let second_reference = object_reference("hadith", "verse:1:1");

        let first = IndexAssignedId::generate(&target, &first_reference);
        let second = IndexAssignedId::generate(&target, &second_reference);

        assert_ne!(first, second);
    }

    #[test]
    fn changing_object_reference_value_changes_assigned_id() {
        let target = target_reference_type("source.object");
        let first_reference = object_reference("quran", "verse:1:1");
        let second_reference = object_reference("quran", "verse:1:2");

        let first = IndexAssignedId::generate(&target, &first_reference);
        let second = IndexAssignedId::generate(&target, &second_reference);

        assert_ne!(first, second);
    }

    #[test]
    fn assigned_id_generation_has_unambiguous_component_boundaries() {
        let first_target = target_reference_type("ab");
        let second_target = target_reference_type("a");

        let first_reference = object_reference("c", "d");
        let second_reference = object_reference("bc", "d");

        let first = IndexAssignedId::generate(&first_target, &first_reference);
        let second = IndexAssignedId::generate(&second_target, &second_reference);

        assert_ne!(first, second);
    }

    #[test]
    fn different_index_assignment_operations_for_the_same_target_share_one_assigned_id() {
        let index_a = IndexId::from_bytes([0x01; INDEX_ID_BYTE_LEN]);
        let index_b = IndexId::from_bytes([0x02; INDEX_ID_BYTE_LEN]);

        let target = target_reference_type("source.object");
        let reference = object_reference("quran", "verse:1:1");

        let assigned_a = IndexAssignedId::generate(&target, &reference);
        let assigned_b = IndexAssignedId::generate(&target, &reference);

        assert_ne!(index_a, index_b);
        assert_eq!(assigned_a, assigned_b);
    }

    #[test]
    fn assigned_id_textual_form_contains_target_type_and_128_hex_digits() {
        let target = target_reference_type("source.object");
        let reference = object_reference("quran", "verse:1:1");
        let id = IndexAssignedId::generate(&target, &reference);

        let text = id.to_string();
        let (prefix, hex) = text
            .rsplit_once('-')
            .expect("assigned ID should contain target type separator");

        assert_eq!(prefix, "source.object");
        assert_eq!(hex.len(), INDEX_ASSIGNED_ID_BYTE_LEN * 2);
        assert!(hex.chars().all(|character| character.is_ascii_hexdigit()));
        assert!(hex.chars().all(|character| !character.is_ascii_uppercase()));
    }

    #[test]
    fn assigned_id_from_parts_preserves_type_and_binary_value() {
        let target = target_reference_type("source.object");
        let bytes = [0xAB; INDEX_ASSIGNED_ID_BYTE_LEN];
        let id = IndexAssignedId::from_parts(target.clone(), bytes);

        assert_eq!(id.target_reference_type(), &target);
        assert_eq!(id.as_bytes(), &bytes);
        assert_eq!(id.into_bytes(), bytes);
    }

    #[test]
    fn assigned_id_hash_is_consistent_for_equal_identity_values() {
        let target = target_reference_type("source.object");
        let reference = object_reference("quran", "verse:1:1");
        let first = IndexAssignedId::generate(&target, &reference);
        let second = IndexAssignedId::generate(&target, &reference);

        let mut first_hasher = DefaultHasher::new();
        first.hash(&mut first_hasher);

        let mut second_hasher = DefaultHasher::new();
        second.hash(&mut second_hasher);

        assert_eq!(first_hasher.finish(), second_hasher.finish());
    }

    #[test]
    fn assigned_id_binary_and_textual_forms_preserve_the_same_identity() {
        let target = target_reference_type("source.object");
        let reference = object_reference("quran", "verse:1:1");
        let id = IndexAssignedId::generate(&target, &reference);

        let rebuilt =
            IndexAssignedId::from_parts(id.target_reference_type().clone(), *id.as_bytes());

        assert_eq!(id, rebuilt);
        assert_eq!(id.to_string(), rebuilt.to_string());
    }

    #[test]
    fn assigned_id_debug_output_identifies_the_type() {
        let target = target_reference_type("source.object");
        let reference = object_reference("quran", "verse:1:1");
        let id = IndexAssignedId::generate(&target, &reference);

        let debug = format!("{id:?}");

        assert!(debug.starts_with("IndexAssignedId {"));
        assert!(debug.contains("target_reference_type"));
        assert!(debug.contains("value"));
    }
}
